# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x63ommon.proto\"\xc3\x01\n\x11TrackingDetection\x12\x13\n\x0b\x66rame_index\x18\x01 \x01(\r\x12\x14\n\x0c\x64\x65tection_id\x18\x02 \x01(\r\x12\x17\n\x0f\x64\x65tection_score\x18\x03 \x01(\x02\x12\r\n\x05\x62ox_x\x18\x04 \x01(\x05\x12\r\n\x05\x62ox_y\x18\x05 \x01(\x05\x12\x11\n\tbox_width\x18\x06 \x01(\x05\x12\x12\n\nbox_height\x18\x07 \x01(\x05\x12%\n\x08\x66\x65\x61tures\x18\x08 \x01(\x0b\x32\x13.AppearanceFeatures\"@\n\x12\x41ppearanceFeatures\x12\x1d\n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\x0b.Appearance\x12\x0b\n\x03\x64im\x18\x02 \x01(\r\"\x1b\n\nAppearance\x12\r\n\x05\x66\x65\x61ts\x18\x01 \x03(\x02*Y\n\rDetectionType\x12\x16\n\x12\x44\x45TECTION_TYPE_SDP\x10\x00\x12\x16\n\x12\x44\x45TECTION_TYPE_DPM\x10\x01\x12\x18\n\x14\x44\x45TECTION_TYPE_FRCNN\x10\x02\x62\x06proto3')
)

_DETECTIONTYPE = _descriptor.EnumDescriptor(
  name='DetectionType',
  full_name='DetectionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DETECTION_TYPE_SDP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DETECTION_TYPE_DPM', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DETECTION_TYPE_FRCNN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=309,
  serialized_end=398,
)
_sym_db.RegisterEnumDescriptor(_DETECTIONTYPE)

DetectionType = enum_type_wrapper.EnumTypeWrapper(_DETECTIONTYPE)
DETECTION_TYPE_SDP = 0
DETECTION_TYPE_DPM = 1
DETECTION_TYPE_FRCNN = 2



_TRACKINGDETECTION = _descriptor.Descriptor(
  name='TrackingDetection',
  full_name='TrackingDetection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_index', full_name='TrackingDetection.frame_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detection_id', full_name='TrackingDetection.detection_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detection_score', full_name='TrackingDetection.detection_score', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='box_x', full_name='TrackingDetection.box_x', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='box_y', full_name='TrackingDetection.box_y', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='box_width', full_name='TrackingDetection.box_width', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='box_height', full_name='TrackingDetection.box_height', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='features', full_name='TrackingDetection.features', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=212,
)


_APPEARANCEFEATURES = _descriptor.Descriptor(
  name='AppearanceFeatures',
  full_name='AppearanceFeatures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='features', full_name='AppearanceFeatures.features', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dim', full_name='AppearanceFeatures.dim', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=278,
)


_APPEARANCE = _descriptor.Descriptor(
  name='Appearance',
  full_name='Appearance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feats', full_name='Appearance.feats', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=307,
)

_TRACKINGDETECTION.fields_by_name['features'].message_type = _APPEARANCEFEATURES
_APPEARANCEFEATURES.fields_by_name['features'].message_type = _APPEARANCE
DESCRIPTOR.message_types_by_name['TrackingDetection'] = _TRACKINGDETECTION
DESCRIPTOR.message_types_by_name['AppearanceFeatures'] = _APPEARANCEFEATURES
DESCRIPTOR.message_types_by_name['Appearance'] = _APPEARANCE
DESCRIPTOR.enum_types_by_name['DetectionType'] = _DETECTIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrackingDetection = _reflection.GeneratedProtocolMessageType('TrackingDetection', (_message.Message,), {
  'DESCRIPTOR' : _TRACKINGDETECTION,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:TrackingDetection)
  })
_sym_db.RegisterMessage(TrackingDetection)

AppearanceFeatures = _reflection.GeneratedProtocolMessageType('AppearanceFeatures', (_message.Message,), {
  'DESCRIPTOR' : _APPEARANCEFEATURES,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:AppearanceFeatures)
  })
_sym_db.RegisterMessage(AppearanceFeatures)

Appearance = _reflection.GeneratedProtocolMessageType('Appearance', (_message.Message,), {
  'DESCRIPTOR' : _APPEARANCE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:Appearance)
  })
_sym_db.RegisterMessage(Appearance)


# @@protoc_insertion_point(module_scope)
